# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: backend-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 10 * * 1,3"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  regressionWithoutCreation:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean test -D"cucumber.filter.tags=@Customer and not @Creation"

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.6
        if: always()
#         id: allure-report
        with:
          allure_results: target/allure-results
#           gh_pages: gh-pages
#           allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
